version: 0.2

env:
  variables:
    REPOSITORY_URI: 387581210505.dkr.ecr.us-east-1.amazonaws.com/udacity3
    REGION: us-east-1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - echo "Building the Docker image with tag: ${CODEBUILD_BUILD_NUMBER}..."
      - #docker build -t $REPOSITORY_URI:${CODEBUILD_BUILD_NUMBER} -f analytics/Dockerfile .
      - #docker tag $REPOSITORY_URI:${CODEBUILD_BUILD_NUMBER} $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Pushing the Docker image with tag: ${CODEBUILD_BUILD_NUMBER} to ECR..."
      - #docker push $REPOSITORY_URI:${CODEBUILD_BUILD_NUMBER}
      - #docker push $REPOSITORY_URI:latest
artifacts:
  files:
    - '**/*'
  discard-paths: yes
